export const test_data = [
    { code: "111111", lecture_name: "디자인커뮤니케이션", class: "01", professor: "윤정식", grade: "03", personnel: "25", department: "디자인건축공학부"},
    { code: "222222", lecture_name: "디자인커뮤니케이션", class: "01", professor: "윤정식", grade: "03", personnel: "25", department: "디자인건축공학부"},
    { code: "333333", lecture_name: "디자인커뮤니케이션", class: "01", professor: "윤정식", grade: "03", personnel: "25", department: "디자인건축공학부"},
    { code: "444444", lecture_name: "디자인커뮤니케이션", class: "01", professor: "윤정식", grade: "03", personnel: "25", department: "디자인건축공학부"},
    { code: "555555", lecture_name: "디자인커뮤니케이션", class: "01", professor: "윤정식", grade: "03", personnel: "25", department: "디자인건축공학부"},
    { code: "666666", lecture_name: "디자인커뮤니케이션", class: "01", professor: "윤정식", grade: "03", personnel: "25", department: "디자인건축공학부"},
    { code: "777777", lecture_name: "디자인커뮤니케이션", class: "01", professor: "윤정식", grade: "03", personnel: "25", department: "디자인건축공학부"},
    { code: "HANPYs", lecture_name: "디자인커뮤니케이션", class: "01", professor: "윤정식", grade: "03", personnel: "25", department: "디자인건축공학부"},
    { code: "HANPYa", lecture_name: "디자인커뮤니케이션", class: "01", professor: "윤정식", grade: "03", personnel: "25", department: "디자인건축공학부"},
    { code: "HANPYb", lecture_name: "디자인커뮤니케이션", class: "01", professor: "윤정식", grade: "03", personnel: "25", department: "디자인건축공학부"},
    { code: "HANPYc", lecture_name: "디자인커뮤니케이션", class: "01", professor: "윤정식", grade: "03", personnel: "25", department: "디자인건축공학부"},
    { code: "HANPYd", lecture_name: "디자인커뮤니케이션", class: "01", professor: "윤정식", grade: "03", personnel: "25", department: "디자인건축공학부"},
    { code: "HANPYe", lecture_name: "디자인커뮤니케이션", class: "01", professor: "윤정식", grade: "03", personnel: "25", department: "디자인건축공학부"},
    { code: "HANPYf", lecture_name: "디자인커뮤니케이션", class: "01", professor: "윤정식", grade: "03", personnel: "25", department: "디자인건축공학부"},
    { code: "HANPYg", lecture_name: "디자인커뮤니케이션", class: "01", professor: "윤정식", grade: "03", personnel: "25", department: "디자인건축공학부"},
    { code: "HANPYh", lecture_name: "디자인커뮤니케이션", class: "01", professor: "윤정식", grade: "03", personnel: "25", department: "디자인건축공학부"},
    { code: "HANPYi", lecture_name: "디자인커뮤니케이션", class: "01", professor: "윤정식", grade: "03", personnel: "25", department: "디자인건축공학부"},
    { code: "HANPYO", lecture_name: "디자인커뮤니케이션", class: "01", professor: "윤정식", grade: "03", personnel: "25", department: "디자인건축공학부"},
];